spring.application.name=restful
api.version = 1.0

# Muestre el mensaje de error de excepciones
server.error.include-message=always

# # Base de datos H2

# # Configuración de la base de datos H2
#     # mem: en memoria
# spring.datasource.url=jdbc:h2:mem:testdb
#     # persistente en archivo
#     # spring.datasource.url=jdbc:h2:file:./data/testdb

# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=

# Configuración JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
    # No permitimos que toque el esquema que vamos a cargar desde shema.sql
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true



# Seguridad
spring.security.user.name=user
spring.security.user.password=pass

# Perfil
spring.profiles.active=dev