-- 1. Creación de la tabla CATEGORIAS (Necesaria para la clave ajena)
-- La clave ajena (FOREIGN KEY) debe referenciar a una clave primaria (PRIMARY KEY).
CREATE TABLE CATEGORIAS (
    -- Clave Primaria
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL
);

-- 2. Creación de la tabla PRODUCTOS
CREATE TABLE PRODUCTOS (
    -- Clave Primaria
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    
    nombre VARCHAR(255) NOT NULL,
    descripcion VARCHAR(1000),
    precio DECIMAL(10, 2) NOT NULL, 
    
    peso DECIMAL(10, 3),        
    altura DECIMAL(10, 2),      
    anchura DECIMAL(10, 2),
    profundidad DECIMAL(10, 2),


    fecha_creacion TIMESTAMP NOT NULL,
    
    -- Clave Ajena (FOREIGN KEY)
    categoria_id BIGINT,
    FOREIGN KEY (categoria_id) REFERENCES CATEGORIAS(id)
);

-- 3- Creamos dos secuencias para los nuevos ids que se creen. Los nuevos tendrán un id superior a 100

DROP SEQUENCE IF EXISTS CATEGORIAS_SEQ;
create SEQUENCE CATEGORIAS_SEQ START WITH 100 INCREMENT BY 1;

DROP SEQUENCE IF EXISTS PRODUCTOS_SEQ;
create SEQUENCE PRODUCTOS_SEQ START WITH 100 INCREMENT BY 1;