package es.etg.daw.dawes.java.rest.restfull.productos.infraestructure.db.jpa.entity;

import jakarta.persistence.*;
import lombok.Data;

@Entity
@Data
@Table(name = "CATEGORIAS")
public class CategoriaJpaEntity {

    // Usamos IDENTITY. H2 lo mapea a 'GENERATED BY DEFAULT AS IDENTITY'.
    // MySQL lo mapea a 'AUTO_INCREMENT'. Es el método más portable.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "nombre", nullable = false, length = 100)
    private String nombre;

    // --- Constructores ---

    public CategoriaJpaEntity() {
    }

    public CategoriaJpaEntity(Long id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
}