package es.etg.daw.dawes.java.rest.restfull.productos.infraestructure.db.jpa.entity;

import jakarta.persistence.*;
import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity
@Data
@Table(name = "PRODUCTOS")
public class ProductoEntity {

    // Usamos IDENTITY. H2 lo mapea a 'GENERATED BY DEFAULT AS IDENTITY'.
    // MySQL lo mapea a 'AUTO_INCREMENT'. Es el método más portable.
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer id;

    @Column(name = "nombre", nullable = false, length = 255)
    private String nombre;

    @Basic(optional=true)
    @Column(name = "descripcion", length = 1000)
    private String descripcion;

    @Column(name = "precio", nullable = false, precision = 10, scale = 2)
    private BigDecimal precio;

    @Column(name = "peso", precision = 10, scale = 3)
    private BigDecimal peso;

    @Column(name = "altura", precision = 10, scale = 2)
    private BigDecimal altura;

    @Column(name = "anchura", precision = 10, scale = 2)
    private BigDecimal anchura;

    @Column(name = "profundidad", precision = 10, scale = 2)
    private BigDecimal profundidad;

    @Column(name = "fecha_creacion", nullable = false)
    private LocalDateTime fechaCreacion;

    // Relación Many-to-One: Es el lado propietario (tendrá la FK)
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "categoria_id", nullable = false) // Columna de clave foránea en la tabla PRODUCTO
    private CategoriaEntity categoria;

    // --- Constructores ---
    public ProductoEntity() {
    }

    // Constructor con campos (simplificado)
    public ProductoEntity(Integer id, String nombre, BigDecimal precio, LocalDateTime fechaCreacion, CategoriaEntity categoria) {
        this.id = id;
        this.nombre = nombre;
        this.precio = precio;
        this.fechaCreacion = fechaCreacion;
        this.categoria = categoria;
    }
    
}